### ISSUE TITLE
Unstable automated tests random crashes (possible 3rd party cause related to PhantomJS).

### ISSUE THREAD

**Issue by jwaliszko** [jwaliszko/ExpressiveAnnotations#102]
To reproduce the issue:
* clone the [project](https://github.com/jwaliszko/ExpressiveAnnotations/tree/450a2252d2802d428389498a9cd1f25b58043b9a),
* open solution in Visual Studio 2015 (Update 1 or above),
* rebuild solution in the RELEASE mode,
* execute [`test1.ps`](https://github.com/jwaliszko/ExpressiveAnnotations/blob/450a2252d2802d428389498a9cd1f25b58043b9a/build/test.ps1) PowerShell script (*multiple execution may be required, issue is non-determinictic*).

You're likely to see the following (or similar, depends on PhantomJS version) errors:

* Selenium `IWebElement.Click()` timeout exception (random failing test shown):
 ```
OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:36739/session/61c45350-d1aa-11e5-9878-b1f29258417c/element/:wdc:1455296622916/click timed out after 15 seconds.
---- System.Net.WebException : The operation has timed out
Stack Trace:
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
D:\Projects\internal\github\ExpressiveAnnotations\src\ExpressiveAnnotations.MvcWebSample.UITests\HomePage.cs(128,0): at ExpressiveAnnotations.MvcWebSample.UITests.HomePage.SafeClick(IWebElement elem)
D:\Projects\internal\github\ExpressiveAnnotations\src\ExpressiveAnnotations.MvcWebSample.UITests\HomePage.cs(35,0): at ExpressiveAnnotations.MvcWebSample.UITests.HomePage.SetMode(String mode)
D:\Projects\internal\github\ExpressiveAnnotations\src\ExpressiveAnnotations.MvcWebSample.UITests\ServerModeTest.cs(14,0): at ExpressiveAnnotations.MvcWebSample.UITests.ServerModeTest..ctor(DriverFixture classContext, Serve
rFixture assemblyContext)
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
```
![image](https://cloud.githubusercontent.com/assets/1596462/13014306/6b15359c-d1b3-11e5-87a8-ff0efde5a278.png)

* `PhantomJSDriver` shutdown hangs:
`[INFO  - 2016-02-12T17:03:07.337Z] ShutdownReqHand - _handle - About to shutdown`
![image](https://cloud.githubusercontent.com/assets/1596462/13013741/06502a74-d1b1-11e5-98ae-9d00521bab24.png)

Note: the tests are executed in parallel - one thread (its own `PhantomJSDriver` instance) tests client-side scenarios (scripts execution only, postbacks to server limited), other thread (separate `PhantomJSDriver` instance) goes through server-side scenarios (postbacks only, validation scripts disabled).

**Comment by jwaliszko** [comment]
Switched to FirefoxDriver.
